clean:
	rm -rf vuln3-32-*

all:
	gcc -fno-stack-protector -m32 -static vuln3-0.c -o vuln3-32-0
	gcc -fno-stack-protector -m32 -static vuln3-1.c -o vuln3-32-1
	gcc -fno-stack-protector -m32 -static vuln3-2.c -o vuln3-32-2
	gcc -fno-stack-protector -m32 -static vuln3-3.c -o vuln3-32-3
	gcc -fno-stack-protector -m32 -static vuln3-4.c -o vuln3-32-4
	gcc -fno-stack-protector -m32 -static vuln3-5.c -o vuln3-32-5
	gcc -fno-stack-protector -m32 -static vuln3-6.c -o vuln3-32-6
	gcc -fno-stack-protector -m32 -static vuln3-7.c -o vuln3-32-7
	gcc -fno-stack-protector -m32 -static vuln3-8.c -o vuln3-32-8
	gcc -fno-stack-protector -m32 -static vuln3-9.c -o vuln3-32-9
	gcc -fno-stack-protector -m32 -static vuln3-10.c -o vuln3-32-10
	gcc -fno-stack-protector -m32 -static vuln3-11.c -o vuln3-32-11
	gcc -fno-stack-protector -m32 -static vuln3-12.c -o vuln3-32-12
	gcc -fno-stack-protector -m32 -static vuln3-13.c -o vuln3-32-13
	gcc -fno-stack-protector -m32 -static vuln3-14.c -o vuln3-32-14
	gcc -fno-stack-protector -m32 -static vuln3-15.c -o vuln3-32-15
	gcc -fno-stack-protector -m32 -static vuln3-16.c -o vuln3-32-16
	gcc -fno-stack-protector -m32 -static vuln3-17.c -o vuln3-32-17
	gcc -fno-stack-protector -m32 -static vuln3-18.c -o vuln3-32-18
	gcc -fno-stack-protector -m32 -static vuln3-19.c -o vuln3-32-19